package com.digiwin.ecims.platforms.ccb.bean.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-16T15:32:18.534+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://index.interfaces.ccb.com/", name = "IntegrationService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IntegrationService {

    @WebResult(name = "return", targetNamespace = "http://index.interfaces.ccb.com/", partName = "return")
    @WebMethod
    public java.lang.String service(
        @WebParam(partName = "arg0", name = "arg0")
        InputData arg0
    );
}
