
package com.digiwin.ecims.platforms.ccb.bean;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.digiwin.ecims.platforms.ccb.bean.webservice.IntegrationService;
import com.digiwin.ecims.platforms.ccb.bean.webservice.IntegrationServiceImplService;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-16T15:32:18.451+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class CcbClient {

    private static final QName SERVICE_NAME = new QName("http://index.interfaces.ccb.com/", "IntegrationServiceImplService");

    public CcbClient() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IntegrationServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IntegrationServiceImplService ss = new IntegrationServiceImplService(wsdlURL, SERVICE_NAME);
        IntegrationService port = ss.getIntegrationServiceImplPort();  
        
        {
        System.out.println("Invoking service...");
        com.digiwin.ecims.platforms.ccb.bean.webservice.InputData _service_arg0 = new com.digiwin.ecims.platforms.ccb.bean.webservice.InputData();
        _service_arg0.setCustId("a");
        _service_arg0.setTranCode("0001");
        _service_arg0.setTranSid(System.currentTimeMillis() + "");
        _service_arg0.setCcbParam("test");
        java.lang.String _service__return = port.service(_service_arg0);
        System.out.println("service.result=" + _service__return);


        }

        System.exit(0);
    }

    public String execute(String tranCode, String custId, String tranSid, String ccbParam) {
      URL wsdlURL = IntegrationServiceImplService.WSDL_LOCATION;
      IntegrationServiceImplService ss = new IntegrationServiceImplService(wsdlURL, SERVICE_NAME);
      IntegrationService port = ss.getIntegrationServiceImplPort();  
      
//      System.out.println("Invoking service...");
      com.digiwin.ecims.platforms.ccb.bean.webservice.InputData _service_arg0 = new com.digiwin.ecims.platforms.ccb.bean.webservice.InputData();
      _service_arg0.setTranCode(tranCode);
      _service_arg0.setCustId(custId);
      _service_arg0.setTranSid(tranSid);
      _service_arg0.setCcbParam(ccbParam);
      java.lang.String _service__return = port.service(_service_arg0);
//      System.out.println("service.result=" + _service__return);
      return _service__return;

    }
}
