package com.digiwin.ecims.ontime.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicUpdate;

import com.digiwin.ecims.ontime.enumvar.TaskGroupTypeEnum;
import com.digiwin.ecims.ontime.enumvar.TaskRunStatusEnum;

/**
* TOntimeTask generated by hbm2java
*/
@SuppressWarnings("serial")
@Entity
@Table(name = "T_ONTIME_TASK")
/*
 * 新增@DynamicUpdate(true)注解标记，如果没有发生变化的字段，在更新时，就不会进行update，
 * 如果不加，就更新所有字段
 */
@DynamicUpdate(true)
public class OntimeTask{

	private long id;
	private String code;
	private String name;
	private String exceType; //@See TaskExceTypeEnum
	private String exceName;
	private long applicationId=0;
	private char isAsyn='Y';
	private String priorityType="1";
	private String cronVal="0 0 1 0 0 ?";
	private String status="1";
	private Date createdDate;
	private Long creatorId;
	private String creatorName;
	private Date modiDate;
	private Long modifierId;
	private String modifierName;
	private String remark;
	@Column(name="remark")
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}


	//利用该字段,可以区分运行的环境,如：Market_web 和 Market_ws 均可以运行定义调用 @Service
	//@See TaskGroupTypeEnum
	private String dataSource=TaskGroupTypeEnum.Platform.getCode();
	
	//定时器程序运行的IP地址限制
	private String runIp = "127.0.0.1";

	//非持久字段,从调度器里查找
	private String runStatus = TaskRunStatusEnum.NO_LOAD.getCode();
	private Long ownerId = 1L;
	public OntimeTask() {
	}

	@Column(name="OWNER_ID")
	public Long getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(Long ownerId) {
		this.ownerId = ownerId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 11)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EXCE_TYPE", nullable = false, length = 8)
	public String getExceType() {
		return this.exceType;
	}

	public void setExceType(String exceType) {
		this.exceType = exceType;
	}

	@Column(name = "EXCE_NAME", nullable = false)
	public String getExceName() {
		return this.exceName;
	}

	public void setExceName(String exceName) {
		this.exceName = exceName;
	}

	@Column(name = "APPLICATION_ID")
	public long getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(long applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "IS_ASYN")
	public char getIsAsyn() {
		return this.isAsyn;
	}

	public void setIsAsyn(char isAsyn) {
		this.isAsyn = isAsyn;
	}

	@Column(name = "PRIORITY_TYPE")
	public String getPriorityType() {
		return this.priorityType;
	}

	public void setPriorityType(String priorityType) {
		this.priorityType = priorityType;
	}

	@Column(name = "CRON_VAL", nullable = false)
	public String getCronVal() {
		return this.cronVal;
	}

	public void setCronVal(String cronVal) {
		this.cronVal = cronVal;
	}

	@Column(name = "STATUS", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATOR_ID")
	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	@Column(name = "CREATOR_NAME")
	public String getCreatorName() {
		return this.creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODI_DATE", length = 11)
	public Date getModiDate() {
		return this.modiDate;
	}

	public void setModiDate(Date modiDate) {
		this.modiDate = modiDate;
	}

	@Column(name = "MODIFIER_ID")
	public Long getModifierId() {
		return this.modifierId;
	}

	public void setModifierId(Long modifierId) {
		this.modifierId = modifierId;
	}

	@Column(name = "MODIFIER_NAME")
	public String getModifierName() {
		return this.modifierName;
	}

	public void setModifierName(String modifierName) {
		this.modifierName = modifierName;
	}

	@Column(name = "DATA_SOURCE", length = 8)
	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	@Column(name = "RUN_IP")
	public String getRunIp() {
		return runIp;
	}

	public void setRunIp(String runIp) {
		this.runIp = runIp;
	}


	@Transient
	public String getRunStatus() {
		return runStatus;
	}


	public void setRunStatus(String runStatus) {
		this.runStatus = runStatus;
	}

	
	
}
