package com.digiwin.ecims.ontime.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicUpdate;
/**
 * TSystemArea generated by hbm2java
 * 
 * 系统参数
 * 
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_SYSTEM_PARAM")
/*
 * 新增@DynamicUpdate(true)注解标记，如果没有发生变化的字段，在更新时，就不会进行update，
 * 如果不加，就更新所有字段
 */
@DynamicUpdate(true)
public class SystemParam {

	
	private String createdDateStr;
	
	private String modiDateStr;
	
	private long id;
	//private SystemParam parent;
	private Long parent;
	private String pKey;
	private String pVal;
	private String pDesc;
	
	private Date createdDate;
	private Long creatorId = new Long(1);
	private String creatorName="sysadmin";
	private Date modiDate;
	private Long modifierId;
	private String modifierName;
	private String dataSource;
	//是否有效
	@Column(name="status")
	private String status;

	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}
//	private List<SystemParam> systemParams = new ArrayList<SystemParam>(0);

	public SystemParam() {
	}
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 11)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	//@ManyToOne(optional=true,fetch = FetchType.LAZY)
	@Column(name = "PARENT_ID")
	public Long getParent() {
		return parent;
	}

	public void setParent(Long parent) {
		this.parent = parent;
	}


	@Column(name = "P_KEY", length = 32)
	public String getpKey() {
		return pKey;
	}


	public void setpKey(String pKey) {
		this.pKey = pKey;
	}


	@Column(name = "P_VAL", length = 256)
	public String getpVal() {
		return pVal;
	}


	public void setpVal(String pVal) {
		this.pVal = pVal;
	}


	@Column(name = "P_DESC", length = 256)
	public String getpDesc() {
		return pDesc;
	}


	public void setpDesc(String pDesc) {
		this.pDesc = pDesc;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 11)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATOR_ID", precision = 12, scale = 0)
	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	@Column(name = "CREATOR_NAME", length = 64)
	public String getCreatorName() {
		return this.creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODI_DATE", length = 11)
	public Date getModiDate() {
		return this.modiDate;
	}

	public void setModiDate(Date modiDate) {
		this.modiDate = modiDate;
	}

	@Column(name = "MODIFIER_ID", precision = 12, scale = 0)
	public Long getModifierId() {
		return this.modifierId;
	}

	public void setModifierId(Long modifierId) {
		this.modifierId = modifierId;
	}

	@Column(name = "MODIFIER_NAME", length = 32)
	public String getModifierName() {
		return this.modifierName;
	}

	public void setModifierName(String modifierName) {
		this.modifierName = modifierName;
	}

	@Column(name = "DATA_SOURCE", length = 8)
	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}
	
	

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parent")
//	public List<SystemParam> getSystemParams() {
//		return this.systemParams;
//	}
//
//	public void setSystemParams(List<SystemParam> systemParams) {
//		this.systemParams = systemParams;
//	}

	@Transient
	public String getCreatedDateStr() {
		return createdDateStr;
	}


	public void setCreatedDateStr(String createdDateStr) {
		this.createdDateStr = createdDateStr;
	}

	@Transient
	public String getModiDateStr() {
		return modiDateStr;
	}


	public void setModiDateStr(String modiDateStr) {
		this.modiDateStr = modiDateStr;
	}


	@Override
	public String toString() {
		return "SystemParam [id=" + id + ", pKey=" + pKey + ", pVal=" + pVal
				+ ", pDesc=" + pDesc + ", createdDate=" + createdDate
				+ ", creatorId=" + creatorId + ", creatorName=" + creatorName
				+ ", modiDate=" + modiDate + ", modifierId=" + modifierId
				+ ", modifierName=" + modifierName + ", dataSource="
				+ dataSource +"]";
	}
	
	

}
